In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("default")
pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:,.2f}".format)

DATA_PATH = "../data/raw/FinanKu_Data_All.csv"

df = pd.read_csv(DATA_PATH)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7561 entries, 0 to 7560
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               7561 non-null   int64
 1   Branch Code               7561 non-null   int64
 2   City                      7561 non-null   object
 3   Age                       7561 non-null   int64
 4   Avg. Annual Income/Month  7561 non-null   int64
 5   Balance Q1                7561 non-null   float64
 6   NumOfProducts Q1          7561 non-null   int64
 7   HasCrCard Q1              7561 non-null   int64
 8   ActiveMember Q1           7561 non-null   int64
 9   Balance Q2                7561 non-null   float64
 10  NumOfProducts Q2          7561 non-null   int64
 11  HasCrCard Q2              7561 non-null   int64
 12  ActiveMember Q2           7561 non-null   int64
 13  Balance Q3                7561 non-null   float64
 14  NumOfProducts Q3          7561 non-null   int64
 15  HasCrCard Q3              7561 non-null   int64
 16  ActiveMember Q3           7561 non-null   int64
 17  Balance Q4                7561 non-null   float64
 18  NumOfProducts Q4          7561 non-null   int64
 19  HasCrCard Q4              7561 non-null   int64
 20  ActiveMember Q4           7561 non-null   int64
 21  Unpaid Tagging            7561 non-null   int64
dtypes: float64(4), int64(17), object(1)
memory usage: 1.3+ MB
HasCrCard Q1
HasCrCard Q1
1    6950
0     611
Name: count, dtype: int64
----------------------------------------
HasCrCard Q2
HasCrCard Q2
1    6950
0     611
Name: count, dtype: int64
----------------------------------------
HasCrCard Q3
HasCrCard Q3
1    6950
0     611
Name: count, dtype: int64
----------------------------------------
HasCrCard Q4
HasCrCard Q4
1    7561
Name: count, dtype: int64
----------------------------------------
ActiveMember Q1
ActiveMember Q1
1    3813
0    3748
Name: count, dtype: int64
----------------------------------------
ActiveMember Q2
ActiveMember Q2
1    3952
0    3609
Name: count, dtype: int64
----------------------------------------
ActiveMember Q3
ActiveMember Q3
1    4130
0    3431
Name: count, dtype: int64
----------------------------------------
ActiveMember Q4
ActiveMember Q4
1    4391
0    3170
Name: count, dtype: int64
----------------------------------------
Unpaid Tagging
Unpaid Tagging
0    5542
1    2019
Name: count, dtype: int64
----------------------------------------

                            dtype  unique  missing         role
Customer ID                 int64    7561        0   Identifier
Branch Code                 int64      18        0  Categorical
City                       object       3        0  Categorical
Age                         int64      49        0    Numerical
Avg. Annual Income/Month    int64      58        0    Numerical
Balance Q1                float64    4929        0    Numerical
NumOfProducts Q1            int64       4        0    Numerical
HasCrCard Q1                int64       2        0       Binary
ActiveMember Q1             int64       2        0       Binary
Balance Q2                float64    5562        0    Numerical
NumOfProducts Q2            int64       5        0    Numerical
HasCrCard Q2                int64       2        0       Binary
ActiveMember Q2             int64       2        0       Binary
Balance Q3                float64    6014        0    Numerical
NumOfProducts Q3            int64       5        0    Numerical
HasCrCard Q3                int64       2        0       Binary
ActiveMember Q3             int64       2        0       Binary
Balance Q4                float64    6399        0    Numerical
NumOfProducts Q4            int64       5        0    Numerical
HasCrCard Q4                int64       1        0       Binary
ActiveMember Q4             int64       2        0       Binary
Unpaid Tagging              int64       2        0       Target

In [19]:
# Dataset
df.shape

rows, cols = df.shape

print(f"Rows : {rows}")
print(f"Columns : {cols}")

Rows : 7561
Columns : 22

In [22]:
# Preview
df.head()

# Random Sample
df.sample(5, random_state=45)

,Customer ID,Branch Code,City,Age,Avg. Annual Income/Month,Balance Q1,NumOfProducts Q1,HasCrCard Q1,ActiveMember Q1,Balance Q2,NumOfProducts Q2,HasCrCard Q2,ActiveMember Q2,Balance Q3,NumOfProducts Q3,HasCrCard Q3,ActiveMember Q3,Balance Q4,NumOfProducts Q4,HasCrCard Q4,ActiveMember Q4,Unpaid Tagging
6432,15738267,1023,Surabaya,59,0,0.00,2,1,1,"1,211,917.54",2,1,1,"1,469,619.54",2,1,1,"1,711,130.54",2,1,1,0
3845,15570060,1024,Surabaya,58,30000000,0.00,2,1,0,0.00,2,1,0,0.00,2,1,0,0.00,2,1,0,1
7084,15782608,1022,Surabaya,37,13000000,0.00,2,1,0,0.00,2,1,0,0.00,2,1,0,0.00,2,1,0,1
1988,15576216,1015,Bandung,61,25000000,0.00,1,1,0,0.00,1,1,0,"326,603.96",1,1,1,"547,791.96",1,1,1,0
1583,15777352,1002,Jakarta,45,31000000,0.00,2,1,1,0.00,2,1,0,0.00,2,1,0,0.00,2,1,0,0

In [ ]:
# Data Type Inspection
df.info()
df.dtypes

# Missing Value Inspection
missing = (
    df.isnull()
    .sum()
    .to_frame("Missing Count")
)

missing["Missing Percentage"] = (
    missing["Missing Count"] / len(df) * 100
)

missing.sort_values(
    "Missing Percentage",
    ascending=False
)

In [ ]:
# Duplicate Inspection
df.duplicated().sum()

# Descriptive Statistics
df.describe().T
df.describe(include="object").T

# Unique Values
df.nunique().sort_values()

# Cardinality Check
pd.DataFrame({
    "dtype": df.dtypes,
    "unique": df.nunique(),
    "missing": df.isna().sum()
})

In [ ]:
# Binary Variable Check
binary_columns = [
    "HasCrCard Q1",
    "HasCrCard Q2",
    "HasCrCard Q3",
    "HasCrCard Q4",
    "ActiveMember Q1",
    "ActiveMember Q2",
    "ActiveMember Q3",
    "ActiveMember Q4",
    "Unpaid Tagging"
]

for col in binary_columns:
    print(col)
    print(df[col].value_counts())
    print("-" * 40)

In [ ]:
# Numeric Summary
numeric_summary = df.describe().T

numeric_summary

# Category Summary
df["City"].value_counts()

# Variable Classification
identifier = [
    "Customer ID"
]

categorical = [
    "Branch Code",
    "City"
]

numerical = [
    "Age",
    "Avg. Annual Income/Month",
    "Balance Q1",
    "Balance Q2",
    "Balance Q3",
    "Balance Q4",
    "NumOfProducts Q1",
    "NumOfProducts Q2",
    "NumOfProducts Q3",
    "NumOfProducts Q4"
]

binary = [
    "HasCrCard Q1",
    "HasCrCard Q2",
    "HasCrCard Q3",
    "HasCrCard Q4",
    "ActiveMember Q1",
    "ActiveMember Q2",
    "ActiveMember Q3",
    "ActiveMember Q4"
]

target = [
    "Unpaid Tagging"
]

# Feature Audit
feature_audit = pd.DataFrame({
    "dtype": df.dtypes,
    "unique": df.nunique(),
    "missing": df.isna().sum()
})

In [23]:
feature_audit

feature_audit.loc["Customer ID", "role"] = "identifier"
# Identifier
feature_audit.loc["Customer ID", "role"] = "Identifier"

# Categorical
feature_audit.loc["Branch Code", "role"] = "Categorical"
feature_audit.loc["City", "role"] = "Categorical"

# Numerical
feature_audit.loc["Age", "role"] = "Numerical"
feature_audit.loc["Avg. Annual Income/Month", "role"] = "Numerical"

feature_audit.loc["Balance Q1", "role"] = "Numerical"
feature_audit.loc["Balance Q2", "role"] = "Numerical"
feature_audit.loc["Balance Q3", "role"] = "Numerical"
feature_audit.loc["Balance Q4", "role"] = "Numerical"

feature_audit.loc["NumOfProducts Q1", "role"] = "Numerical"
feature_audit.loc["NumOfProducts Q2", "role"] = "Numerical"
feature_audit.loc["NumOfProducts Q3", "role"] = "Numerical"
feature_audit.loc["NumOfProducts Q4", "role"] = "Numerical"

# Binary
feature_audit.loc["HasCrCard Q1", "role"] = "Binary"
feature_audit.loc["HasCrCard Q2", "role"] = "Binary"
feature_audit.loc["HasCrCard Q3", "role"] = "Binary"
feature_audit.loc["HasCrCard Q4", "role"] = "Binary"

feature_audit.loc["ActiveMember Q1", "role"] = "Binary"
feature_audit.loc["ActiveMember Q2", "role"] = "Binary"
feature_audit.loc["ActiveMember Q3", "role"] = "Binary"
feature_audit.loc["ActiveMember Q4", "role"] = "Binary"

# Target
feature_audit.loc["Unpaid Tagging", "role"] = "Target"

feature_audit

                            dtype  unique  missing         role
Customer ID                 int64    7561        0   Identifier
Branch Code                 int64      18        0  Categorical
City                       object       3        0  Categorical
Age                         int64      49        0    Numerical
Avg. Annual Income/Month    int64      58        0    Numerical
Balance Q1                float64    4929        0    Numerical
NumOfProducts Q1            int64       4        0    Numerical
HasCrCard Q1                int64       2        0       Binary
ActiveMember Q1             int64       2        0       Binary
Balance Q2                float64    5562        0    Numerical
NumOfProducts Q2            int64       5        0    Numerical
HasCrCard Q2                int64       2        0       Binary
ActiveMember Q2             int64       2        0       Binary
Balance Q3                float64    6014        0    Numerical
NumOfProducts Q3            int64       5        0    Numerical
HasCrCard Q3                int64       2        0       Binary
ActiveMember Q3             int64       2        0       Binary
Balance Q4                float64    6399        0    Numerical
NumOfProducts Q4            int64       5        0    Numerical
HasCrCard Q4                int64       1        0       Binary
ActiveMember Q4             int64       2        0       Binary
Unpaid Tagging              int64       2        0       Target